/*
 * kernel/nn_infer.h — Neural network inference engine interface
 *
 * Declares the forward-pass inference function for the trained MLP scheduler.
 * The weight values are stored in include/nn_weights.h (auto-generated by
 * scripts/train.py after Phase 3 training).
 *
 * Architecture: 5 inputs → 8 hidden (ReLU) → 1 output (Sigmoid)
 * Total parameters: (5×8 + 8) + (8×1 + 1) = 57 floats (~228 bytes)
 *
 * The FPU is enabled at boot, so standard float arithmetic is available.
 */

#ifndef NN_INFER_H
#define NN_INFER_H

#include <stdint.h>
#include "process.h"

/*
 * nn_score_process — Run the MLP forward pass for a single candidate process.
 *
 * Builds the normalized feature vector from the process's current state,
 * runs the network, and returns the output Sigmoid value ∈ (0, 1).
 *
 * A higher score means the model thinks this process should run next.
 *
 * p            : The process to evaluate.
 * max_wait     : The maximum wait_ticks observed across all ready processes
 *                (used for min-max normalization of the wait_ticks feature).
 * max_burst    : The maximum remaining_burst across all ready processes
 *                (used for normalization).
 *
 * Returns: float in (0, 1) — the process's scheduling score.
 */
float nn_score_process(const process_t *p, uint32_t max_wait,
                       uint32_t max_burst);

/*
 * nn_select_process — Score all READY processes and return the index of the
 * best candidate. Also fills *confidence_out with the winning score.
 *
 * If confidence is below NN_CONF_THRESH (from nn_weights.h), the caller
 * (run_neural_scheduler) should fall back to round-robin.
 *
 * procs[]          : Process array.
 * n_procs          : Number of processes.
 * confidence_out   : Output pointer — filled with the winner's score.
 *
 * Returns: index into procs[] of the selected process,
 *          or -1 if no READY process exists.
 */
int nn_select_process(process_t procs[], int n_procs,
                      float *confidence_out);

#endif /* NN_INFER_H */
