/*
 * include/nn_weights.h — Trained Neural Network Weights
 * AUTO-GENERATED by scripts/train.py on 2026-08-11 00:33:53
 * DO NOT EDIT MANUALLY — run 'python scripts/train.py' to regenerate
 *
 * Architecture: 5 inputs -> 8 hidden (ReLU) -> 1 output (Sigmoid)
 * Parameters: 57 floats = 228 bytes
 */

#ifndef NN_WEIGHTS_H
#define NN_WEIGHTS_H

/* Architecture Dimensions */
#define NN_INPUT_DIM    5
#define NN_HIDDEN_DIM   8
#define NN_OUTPUT_DIM   1

/* Confidence fallback threshold: if NN output < this, use round-robin */
#define NN_CONF_THRESH  0.65f

/* Feature normalization: priority range */
#define NN_FEAT_MIN_PRIORITY    1.000000f
#define NN_FEAT_MAX_PRIORITY    5.000000f

/* Feature normalization: io_yield_count range */
#define NN_FEAT_MIN_IO_YIELD    0.000000f
#define NN_FEAT_MAX_IO_YIELD    7.000000f

/* Layer 1 Weights: W1[INPUT_DIM][HIDDEN_DIM] */
static const float W1[5][8] = {
    /* feat[0]=wait_ticks           */  { 0.757983f, -0.657744f, 0.049330f, 0.740975f, -1.235276f, -1.102037f, 0.756407f, -0.198483f },
    /* feat[1]=remaining_burst      */  { -0.365762f, -0.539512f, 0.870796f, 0.424502f, 0.042876f, 0.530854f, 0.151181f, -0.545156f },
    /* feat[2]=priority             */  { 0.834388f, -0.606451f, 0.167211f, 0.109699f, -0.145834f, -1.115921f, 1.232741f, -0.081293f },
    /* feat[3]=io_bound             */  { -0.069196f, -0.222709f, 0.672681f, 0.061976f, 0.249176f, -0.008234f, 0.909086f, -0.257765f },
    /* feat[4]=io_yield_count       */  { 0.067819f, -0.514675f, 0.238444f, 0.777776f, -0.065325f, 0.010368f, -0.361728f, 0.412147f },
};

/* Layer 1 Biases: B1[HIDDEN_DIM] */
static const float B1[NN_HIDDEN_DIM] = {
    -0.072810f, 0.000000f, 0.659202f, -0.051183f, -0.014699f, 0.679151f, -0.035803f, -0.000725f
};

/* Layer 2 Weights: W2[HIDDEN_DIM][OUTPUT_DIM] */
static const float W2[8][1] = {
    { 1.120886f },
    { 0.271577f },
    { -0.853417f },
    { 0.482575f },
    { -0.087862f },
    { -1.219947f },
    { 0.684321f },
    { 0.108189f },
};

/* Layer 2 Bias: B2[OUTPUT_DIM] */
static const float B2[NN_OUTPUT_DIM] = {
    -1.413928f
};

#endif /* NN_WEIGHTS_H */
