/*
 * include/nn_weights.h — Trained Neural Network Weights
 * AUTO-GENERATED by scripts/train.py on 2026-08-10 19:57:12
 * DO NOT EDIT MANUALLY — run 'python scripts/train.py' to regenerate
 *
 * Architecture: 5 inputs -> 8 hidden (ReLU) -> 1 output (Sigmoid)
 * Parameters: 57 floats = 228 bytes
 */

#ifndef NN_WEIGHTS_H
#define NN_WEIGHTS_H

/* Architecture Dimensions */
#define NN_INPUT_DIM    5
#define NN_HIDDEN_DIM   8
#define NN_OUTPUT_DIM   1

/* Confidence fallback threshold: if NN output < this, use round-robin */
#define NN_CONF_THRESH  0.65f

/* Feature normalization: priority range */
#define NN_FEAT_MIN_PRIORITY    1.000000f
#define NN_FEAT_MAX_PRIORITY    5.000000f

/* Feature normalization: io_yield_count range */
#define NN_FEAT_MIN_IO_YIELD    0.000000f
#define NN_FEAT_MAX_IO_YIELD    7.000000f

/* Layer 1 Weights: W1[INPUT_DIM][HIDDEN_DIM] */
static const float W1[5][8] = {
    /* feat[0]=wait_ticks           */  { 0.759053f, -0.657744f, 0.030744f, 0.760888f, -1.235109f, -0.779121f, 0.745115f, -0.200179f },
    /* feat[1]=remaining_burst      */  { -0.199834f, -0.539512f, 0.961235f, 0.370434f, 0.038790f, 0.802919f, 0.073673f, -0.543732f },
    /* feat[2]=priority             */  { 0.823482f, -0.606451f, 0.147769f, 0.127664f, -0.126437f, -0.436794f, 1.250871f, -0.096365f },
    /* feat[3]=io_bound             */  { -0.180203f, -0.222709f, 0.644559f, 0.098559f, 0.241878f, 0.289161f, 0.983742f, -0.259241f },
    /* feat[4]=io_yield_count       */  { 0.059687f, -0.514675f, 0.217091f, 0.795258f, -0.079094f, -0.516832f, -0.337824f, 0.409716f },
};

/* Layer 1 Biases: B1[HIDDEN_DIM] */
static const float B1[NN_HIDDEN_DIM] = {
    0.011217f, 0.000000f, 0.715206f, -0.135401f, -0.019698f, 0.191495f, -0.157350f, -0.002201f
};

/* Layer 2 Weights: W2[HIDDEN_DIM][OUTPUT_DIM] */
static const float W2[8][1] = {
    { 1.092091f },
    { 0.271577f },
    { -0.958826f },
    { 0.501404f },
    { -0.013965f },
    { -0.337314f },
    { 0.788284f },
    { 0.110860f },
};

/* Layer 2 Bias: B2[OUTPUT_DIM] */
static const float B2[NN_OUTPUT_DIM] = {
    -1.376241f
};

#endif /* NN_WEIGHTS_H */
